In [13]:
import pandas as pd
import osgb
import numpy as np
import os

In [2]:
data = pd.read_csv('pythobook.csv')
data.head()

,SampleNumber,ProductionArea,BedID,LocalAuthority,GridReference,SamplingPoint,DateSampleCollected,PSP-Alexandrium_spp.CellsL-1,DSP-DinophysiaceaeCellsL-1,DSP-ProrocentrumLimaCellsL-1,...,DSP-ProrocentrumLimaCellsL-1 (groups),PSP-Alexandrium_spp.CellsL-1 (groups),DSP-DinophysiaceaeCellsL-1 (groups),ASP-Pseudo-nitzschia_spp.CellsL-1 (groups),YessotoxinLingulodiniumPolyedrumCellsL-1 (groups),YessotoxinProtoceratiumReticulatumCellsL-1 (groups),VenerupinProrocentrumCordatumCellsL-1 (groups),Case Possible,Abnormally High Cases,Total Abnormal Cases
0,23/20,Fal,B033E,Cornwall PHA,SW85134212,Grimes Bar,1/20/2020 0:00,ND,ND,ND,...,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Unsure,Unsure,36
1,24/20,Fal,B33BD,Cornwall PHA,SW84093949,Trelissick Pontoon,1/20/2020 0:00,ND,ND,ND,...,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Unsure,Unsure,36
2,47/20,Fal,B33BG,Cornwall PHA,SW82803517,Mylor Pool,1/28/2020 0:00,ND,ND,ND,...,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Unsure,Unsure,36
3,48/20,Percuil,B033R,Cornwall PHA,SW85853369,Percuil,1/28/2020 0:00,ND,ND,ND,...,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Unsure,Unsure,36
4,52/20,Fal,B033E,Cornwall PHA,SW85134212,Grimes Bar,2/4/2020 0:00,ND,ND,ND,...,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Not Tested,Unsure,Unsure,36

In [3]:
def grid_ref_to_coords(grid_ref):
    try:
        (easting, northing) = osgb.parse_grid(grid_ref)
        (lat, lon) = osgb.grid_to_ll(easting, northing)
        return lat, lon
    except:
        return -1, -1

grid_ref_to_coords("SW85134212")

(50.239915, -5.01475)

In [4]:
data['GridReference'].unique()

array(['SW85134212', 'SW84093949', 'SW82803517', 'SW85853369',
       'SW75462765', 'SW85024095', 'SW81963551', 'SX16305094',
       'SX05744972', 'SW80212383', 'SX13025157', 'SX05214698',
       'SW83663789', 'TQ90429738', 'TL91160795', 'TM04060768',
       'TL89310707', 'TQ88148489', 'TR06779599', 'TR00508769',
       'TQ93798271', 'TQ94909207', 'TM39434850', 'TM28834500',
       'TM00001301', 'SU48760530', 'SS46573142', 'SY66477627',
       'SH76317972', 'TR10326689', 'TF65963701', 'SS87114787',
       'TF79884539', 'TF91804549', 'TR01316497', 'NU12333958',
       'SS67659210', 'SU70560339', 'SX87415599', 'SX92827284',
       'SD34194862', 'SD23116464', 'SY45918886', 'SX54224904',
       'SU62850544', 'SU40280013', 'SZ01818871', 'TF44234098',
       'SX97948072', 'SW93407530', 'SX87945350', 'SX84724671',
       'SX90965741', 'SY68918032', 'SX67114467', 'SH49916579',
       'SZ57479794', 'SH58337328', 'SM89000275', 'SJ17568056',
       'UNVERIFIED', 'SH53148022', 'SS87184778', 'SY68707757',
       'SM72582343', 'SS46403160', 'SS50209860', 'SS50509590',
       'SS43409470', 'SX82504197', 'SX93996191', 'SH67528109',
       'SX02264678', nan], dtype=object)

In [5]:
ret = pd.DataFrame()
ret['Grid'] = data['GridReference'].unique()

In [6]:
ret.head()

         Grid
0  SW85134212
1  SW84093949
2  SW82803517
3  SW85853369
4  SW75462765

In [8]:
def long_from_osgb(x):
    return grid_ref_to_coords(x)[1]

def lat_from_osgb(x):
    return grid_ref_to_coords(x)[0]

In [9]:
ret['Longitude'] = ret['Grid'].apply(lambda x: long_from_osgb(x))
ret['Latitude'] = ret['Grid'].apply(lambda x: lat_from_osgb(x))

In [10]:
ret.head(10)

         Grid  Longitude   Latitude
0  SW85134212  -5.014750  50.239915
1  SW84093949  -5.027816  50.215916
2  SW82803517  -5.043401  50.176647
3  SW85853369  -4.999913  50.164465
4  SW75462765  -5.141613  50.106380
5  SW85024095  -5.015627  50.229367
6  SW81963551  -5.055343  50.179392
7  SX16305094  -4.582410  50.329669
8  SX05744972  -4.729980  50.315322
9  SW80212383  -5.073089  50.073851

In [14]:
path = r'../Phytoplankton'
ret.to_csv(os.path.join(path,r'coords.csv'))